### ISSUE TITLE
Make contact form more responsive

### ISSUE THREAD

**Issue by LemonFace0309** [LemonFace0309/msmr#108]
![image](https://user-images.githubusercontent.com/65472533/113127691-09092800-91e7-11eb-9d81-5dc843c7f637.png)

**Comment by functionstackx** [comment]
@LemonFace0309 I wanna add on to this issue.

Is there a way to set a max-width to this component too? so it does not infinity stretch

![image](https://user-images.githubusercontent.com/47992694/113457981-505a0900-93df-11eb-9fe3-88fe92033d0a.png)

**Comment by LemonFace0309** [comment]
Yeah, will do. Thanks for bringing that up. I also have to work on some weird margin/padding bugs it creates on smaller viewports. It currently expands beyond 100vw on phone screens.
