### ISSUE TITLE
Social Images to Icons

### ISSUE THREAD

**Issue by jimmyygit** [LemonFace0309/msmr#42]
![image](https://user-images.githubusercontent.com/68363001/108409544-5cee1d80-71f4-11eb-9b55-04014f9bef7f.png)

I didn't realize these were images. The same thing can be achieved with icons and it saves the hassle of loading images.
Font-awesome should have all these icons

**Comment by functionstackx** [comment]
@jimmyygit  is font-awesome an svg?

do we need to load in another library or cdn? or do we just attach a image URL?

**Comment by jimmyygit** [comment]
> @jimmyygit is font-awesome an svg?
> 
> do we need to load in another library or cdn? or do we just attach a image URL?

its just a link to a cdn

**Comment by functionstackx** [comment]
ok, i moved this to the backlog. this is probably something we can do at a (optimization)/later sprint
