### ISSUE TITLE
Dynamic Card sizing

### ISSUE THREAD

**Issue by wx02shi** [LemonFace0309/msmr#47]
Here we can see misalignment of the bottom of the cards. The height of a card is affected by:
1. The size of the image
2. The length of the text used

![image](https://user-images.githubusercontent.com/33271663/108551207-9c347100-72bd-11eb-8cfe-ac81f06a745d.png)

**Comment by functionstackx** [comment]
@williamsxz99 is this still an issue or was it resolved after the standup today with @LemonFace0309 ?
