### ISSUE TITLE
Static File Serving

### ISSUE THREAD

**Issue by LemonFace0309** [LemonFace0309/msmr#50]
Images are rendering slower than text on cold starts. Not sure if normal image tags are better for SSG than next/image tag.

**Comment by functionstackx** [comment]
Issue discussed on this PR: https://github.com/Cache-and-Cookies/msmr/pull/45

**Comment by functionstackx** [comment]
Additional Resources to read up on:

https://stackoverflow.com/questions/62860798/preloading-images-in-nextjs

https://nextjs.org/docs/basic-features/static-file-serving

![image](https://user-images.githubusercontent.com/47992694/108578872-48904a80-72f2-11eb-9ea8-0ae6e3f801c6.png)
