### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by LemonFace0309** [LemonFace0309/msmr#51]

**Comment by functionstackx** [comment]
@LemonFace0309 do you want to describe the animations in a bit more detail? 

like where, how, what?

**Comment by LemonFace0309** [comment]
> @LemonFace0309 do you want to describe the animations in a bit more detail? 
> 
> like where, how, what?

I was planning on discussing it in more detail for next sprint.

**Comment by LemonFace0309** [comment]
Just added to backlog so I don't forget
