### ISSUE TITLE
Home Page - Resarching Resilence

### ISSUE THREAD

**Issue by functionstackx** [LemonFace0309/msmr#7]
![image](https://user-images.githubusercontent.com/47992694/108106000-5f693f80-705b-11eb-834c-9819bc6c485b.png)

**Comment by functionstackx** [comment]
@jimmyygit remember to state the reason if you reopening an issue or PR

**Comment by jimmyygit** [comment]
> @jimmyygit remember to state the reason if you reopening an issue or PR

i think i closed the issue by accident
